#### Boosting Methods

In [1]:
## Loading required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

#### Reading Both Train Data and Test Data

In [2]:
traindata      =  pd.read_csv("C:/Users/sirola/Downloads/CUTe/Traindata.csv")
validationdata =  pd.read_csv("C:/Users/sirola/Downloads/CUTe/Validationdata.csv")

In [3]:
traindata.shape

(19684, 34)

In [4]:
validationdata.shape

(8436, 34)

In [5]:
traindata.columns

Index(['Unnamed: 0', 'Attr1', 'Attr3', 'Attr5', 'Attr6', 'Attr8', 'Attr13',
       'Attr15', 'Attr19', 'Attr24', 'Attr25', 'Attr26', 'Attr27', 'Attr28',
       'Attr29', 'Attr30', 'Attr36', 'Attr39', 'Attr40', 'Attr41', 'Attr42',
       'Attr45', 'Attr46', 'Attr47', 'Attr48', 'Attr52', 'Attr53', 'Attr55',
       'Attr57', 'Attr59', 'Attr60', 'Attr61', 'Attr63', 'target'],
      dtype='object')

In [6]:
## dropping the target variable
x_train = traindata.drop(["target"],axis=1)

In [7]:
## dropping the target variable
x_test = validationdata.drop(["target"],axis=1)

In [8]:
## creating another dataframe with target variable
y_train = traindata['target']
y_test = validationdata['target']

### Building Adaboost Classifier

In [9]:
# importing required modules 
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

In [10]:
# Creating adaboost-decision tree classifer object
Adaboost_model = AdaBoostClassifier(
    DecisionTreeClassifier(max_depth=2),
    n_estimators = 600,
    learning_rate = 1
)

In [11]:
# Training the model on the data
%time Adaboost_model.fit(x_train, y_train)

Wall time: 6min 24s


AdaBoostClassifier(algorithm='SAMME.R',
          base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=2,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
          learning_rate=1, n_estimators=600, random_state=None)

In [12]:
# Predict on Test 
y_preds = Adaboost_model.predict(x_test)

In [13]:
# Verify accuracy
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_preds))

0.9649122807017544


In [14]:
y_pred = Adaboost_model.predict(x_train)

# Verify accuracy
from sklearn.metrics import accuracy_score
print(accuracy_score(y_train, y_pred))

1.0


In [16]:
# Import classification report and confusion matrix to evaluate predictions
from sklearn.metrics import classification_report, confusion_matrix
# Print out classification report 
print(classification_report(y_test,y_preds))
# Print out confusion matrix
cmat = confusion_matrix(y_test, y_preds)
print(cmat)
sensitivity1 = cmat[0,0]/(cmat[0,0]+cmat[0,1])
print('Sensitivity : ', sensitivity1 )
print('Accuracy Rate: {}'.format(np.divide(np.sum([cmat[0,0],cmat[1,1]]),np.sum(cmat))))
specificity1 = cmat[1,1]/(cmat[1,0]+cmat[1,1])
print('Specificity : ', specificity1)


             precision    recall  f1-score   support

          0       0.97      0.97      0.97      4650
          1       0.96      0.96      0.96      3786

avg / total       0.96      0.96      0.96      8436

[[4501  149]
 [ 147 3639]]
Sensitivity :  0.9679569892473119
Accuracy Rate: 0.9649122807017544
Specificity :  0.9611727416798732


In [18]:
# Print out classification report 
print(classification_report(y_train,y_pred))
cmat1 = confusion_matrix(y_train,y_pred)
print(cmat1)
sensitivity2 = cmat1[0,0]/(cmat1[0,0]+cmat1[0,1])
print('Sensitivity : ', sensitivity2 )
print('Accuracy Rate: {}'.format(np.divide(np.sum([cmat1[0,0],cmat1[1,1]]),np.sum(cmat1))))
specificity2 = cmat1[1,1]/(cmat1[1,0]+cmat1[1,1])
print('Specificity : ', specificity2)

             precision    recall  f1-score   support

          0       1.00      1.00      1.00     10972
          1       1.00      1.00      1.00      8712

avg / total       1.00      1.00      1.00     19684

[[10972     0]
 [    0  8712]]
Sensitivity :  1.0
Accuracy Rate: 1.0
Specificity :  1.0


#### Grid Search for getting better hyperparameters

In [19]:
from sklearn.model_selection import GridSearchCV

param_grid = {'n_estimators' : [100, 150, 200],
              'learning_rate' : [0.1, 0.5, 0.9]}

Adaboost_model_clf = GridSearchCV(AdaBoostClassifier(
            DecisionTreeClassifier(max_depth=2)), param_grid, n_jobs=4)

In [20]:
# Train model
%time Adaboost_model_clf.fit(x_train, y_train)

Wall time: 6min 54s


GridSearchCV(cv=None, error_score='raise',
       estimator=AdaBoostClassifier(algorithm='SAMME.R',
          base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=2,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
          learning_rate=1.0, n_estimators=50, random_state=None),
       fit_params=None, iid=True, n_jobs=4,
       param_grid={'n_estimators': [100, 150, 200], 'learning_rate': [0.1, 0.5, 0.9]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [21]:
# Find best model
best_ada_model = Adaboost_model_clf.best_estimator_
print (Adaboost_model_clf.best_score_, Adaboost_model_clf.best_params_) 

0.9451331030278398 {'learning_rate': 0.9, 'n_estimators': 200}


In [22]:
## prediction on test set
y_pred_test=best_ada_model.predict(x_test)

In [23]:
# Verify accuracy
print(accuracy_score(y_test,y_pred_test))

0.9513987671882409


In [24]:
# Create adaboost-decision tree classifer object
Adaboost_model = AdaBoostClassifier(
    DecisionTreeClassifier(max_depth=2),
    n_estimators = 200,
    learning_rate = 0.8
)

%time Adaboost_model.fit(x_train, y_train)

# Predict on Test 
y_preds_train = Adaboost_model.predict(x_train)
y_preds_test = Adaboost_model.predict(x_test)

print("Train Accuracy", accuracy_score(y_train, y_preds_train))
print("Test Accuracy", accuracy_score(y_test, y_preds_test))

Wall time: 2min 17s
Train Accuracy 0.9771895956106482
Test Accuracy 0.9481981981981982


In [25]:
# Print out classification report 
print(classification_report(y_test,y_preds_test))
#Print out confusion matrix
cmat = confusion_matrix(y_test, y_preds_test)
print(cmat)
sensitivity1 = cmat[0,0]/(cmat[0,0]+cmat[0,1])
print('Sensitivity : ', sensitivity1 )
print('Accuracy Rate: {}'.format(np.divide(np.sum([cmat[0,0],cmat[1,1]]),np.sum(cmat))))
specificity1 = cmat[1,1]/(cmat[1,0]+cmat[1,1])
print('Specificity : ', specificity1)


             precision    recall  f1-score   support

          0       0.95      0.96      0.95      4650
          1       0.95      0.94      0.94      3786

avg / total       0.95      0.95      0.95      8436

[[4447  203]
 [ 234 3552]]
Sensitivity :  0.9563440860215053
Accuracy Rate: 0.9481981981981982
Specificity :  0.9381933438985737


In [26]:
# Print out classification report 
print(classification_report(y_train,y_preds_train))
cmat1 = confusion_matrix(y_train,y_preds_train)
print(cmat1)
sensitivity2 = cmat1[0,0]/(cmat1[0,0]+cmat1[0,1])
print('Sensitivity : ', sensitivity2 )
print('Accuracy Rate: {}'.format(np.divide(np.sum([cmat1[0,0],cmat1[1,1]]),np.sum(cmat1))))
specificity2 = cmat1[1,1]/(cmat1[1,0]+cmat1[1,1])
print('Specificity : ', specificity2)

             precision    recall  f1-score   support

          0       0.98      0.98      0.98     10972
          1       0.98      0.97      0.97      8712

avg / total       0.98      0.98      0.98     19684

[[10772   200]
 [  249  8463]]
Sensitivity :  0.98177178271965
Accuracy Rate: 0.9771895956106482
Specificity :  0.9714187327823691


### Building Gradient Boosting Classifier

In [27]:
from sklearn.ensemble import GradientBoostingClassifier

In [28]:
GBM_model = GradientBoostingClassifier(n_estimators=50,
                                       learning_rate=0.3,
                                       subsample=0.8)

### Training the model on the data

In [29]:
%time GBM_model.fit(X=x_train, y=y_train)

Wall time: 14.1 s


GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.3, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=50,
              presort='auto', random_state=None, subsample=0.8, verbose=0,
              warm_start=False)

#### Predicting the model on the test data

In [30]:
y_pred = GBM_model.predict(x_test)

#### Checking accuracy

In [31]:
print(accuracy_score(y_test,y_pred))

0.9186818397344713


In [32]:
y_preds = GBM_model.predict(x_train)

# Verify accuracy
from sklearn.metrics import accuracy_score
print(accuracy_score(y_train, y_preds))

0.9304003251371672


In [33]:
# Print out classification report 
print(classification_report(y_test,y_pred))
# Print out confusion matrix
cmat = confusion_matrix(y_test, y_pred)
print(cmat)
sensitivity1 = cmat[0,0]/(cmat[0,0]+cmat[0,1])
print('Sensitivity : ', sensitivity1 )
print('Accuracy Rate: {}'.format(np.divide(np.sum([cmat[0,0],cmat[1,1]]),np.sum(cmat))))
specificity1 = cmat[1,1]/(cmat[1,0]+cmat[1,1])
print('Specificity : ', specificity1)


             precision    recall  f1-score   support

          0       0.92      0.94      0.93      4650
          1       0.92      0.90      0.91      3786

avg / total       0.92      0.92      0.92      8436

[[4360  290]
 [ 396 3390]]
Sensitivity :  0.9376344086021505
Accuracy Rate: 0.9186818397344713
Specificity :  0.8954041204437401


In [34]:
# Print out classification report 
print(classification_report(y_train,y_preds))
cmat1 = confusion_matrix(y_train,y_preds)
print(cmat1)
sensitivity2 = cmat1[0,0]/(cmat1[0,0]+cmat1[0,1])
print('Sensitivity : ', sensitivity2 )
print('Accuracy Rate: {}'.format(np.divide(np.sum([cmat1[0,0],cmat1[1,1]]),np.sum(cmat1))))
specificity2 = cmat1[1,1]/(cmat1[1,0]+cmat1[1,1])
print('Specificity : ', specificity2)

             precision    recall  f1-score   support

          0       0.93      0.95      0.94     10972
          1       0.93      0.91      0.92      8712

avg / total       0.93      0.93      0.93     19684

[[10396   576]
 [  794  7918]]
Sensitivity :  0.947502734232592
Accuracy Rate: 0.9304003251371672
Specificity :  0.9088613406795225


###  Using Gridsearch for getting better hyperparameters

In [35]:
from sklearn.grid_search import GridSearchCV

# Model in use
GBM = GradientBoostingClassifier() 
 
# Use a grid over parameters of interest
param_grid = { 
           "n_estimators" : [100,150,200],
           "max_depth" : [5, 10],
           "learning_rate" : [0.1,0.5,0.9]}
 
CV_GBM = GridSearchCV(estimator=GBM, param_grid=param_grid, cv= 5)

E:\PYTHON\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
E:\PYTHON\lib\site-packages\sklearn\grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)


#### XGBM

In [36]:
!pip install xgboost
from xgboost import XGBClassifier
XGB_model = XGBClassifier()

distributed 1.21.8 requires msgpack, which is not installed.
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [37]:
%time XGB_model.fit(x_train, y_train)

Wall time: 25.2 s


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='binary:logistic', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [38]:
print(XGB_model)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='binary:logistic', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)


In [39]:
x_train.shape

(19684, 33)

#### predicting on test set

In [40]:
import warnings
warnings.filterwarnings(action='ignore', category=DeprecationWarning)

In [41]:
y_pred = XGB_model.predict(x_test)

###  Accuracy

In [42]:
print(accuracy_score(y_test,y_pred))

0.9059981033665244


In [43]:
y_preds = XGB_model.predict(x_train)

# Verify accuracy
from sklearn.metrics import accuracy_score
print(accuracy_score(y_train, y_preds))

0.9168868116236537


In [44]:
# Print out classification report 
print(classification_report(y_test,y_pred))
# Print out confusion matrix
cmat = confusion_matrix(y_test, y_pred)
print(cmat)
sensitivity1 = cmat[0,0]/(cmat[0,0]+cmat[0,1])
print('Sensitivity : ', sensitivity1 )
print('Accuracy Rate: {}'.format(np.divide(np.sum([cmat[0,0],cmat[1,1]]),np.sum(cmat))))
specificity1 = cmat[1,1]/(cmat[1,0]+cmat[1,1])
print('Specificity : ', specificity1)


             precision    recall  f1-score   support

          0       0.90      0.93      0.92      4650
          1       0.91      0.87      0.89      3786

avg / total       0.91      0.91      0.91      8436

[[4338  312]
 [ 481 3305]]
Sensitivity :  0.9329032258064516
Accuracy Rate: 0.9059981033665244
Specificity :  0.8729529846804015


In [45]:
# Print out classification report 
print(classification_report(y_train,y_preds))
cmat1 = confusion_matrix(y_train,y_preds)
print(cmat1)
sensitivity2 = cmat1[0,0]/(cmat1[0,0]+cmat1[0,1])
print('Sensitivity : ', sensitivity2 )
print('Accuracy Rate: {}'.format(np.divide(np.sum([cmat1[0,0],cmat1[1,1]]),np.sum(cmat1))))
specificity2 = cmat1[1,1]/(cmat1[1,0]+cmat1[1,1])
print('Specificity : ', specificity2)

             precision    recall  f1-score   support

          0       0.91      0.94      0.93     10972
          1       0.92      0.89      0.90      8712

avg / total       0.92      0.92      0.92     19684

[[10331   641]
 [  995  7717]]
Sensitivity :  0.9415785636164783
Accuracy Rate: 0.9168868116236537
Specificity :  0.8857897153351699


## Grid Search Using Cross Validation

In [46]:
from sklearn.grid_search import GridSearchCV
XGB = XGBClassifier(n_jobs=-1)
 
# Use a grid over parameters of interest
param_grid = {
     'colsample_bytree': np.linspace(0.5, 0.9, 2),
     'n_estimators':[100, 200],
     'max_depth': [10, 15, 20]
}

 
CV_XGB = GridSearchCV(estimator=XGB, param_grid=param_grid, cv= 5)

### Training the XGBOOST Classifier 

In [47]:
%time CV_XGB.fit(X=x_train, y=y_train)

Wall time: 59min 49s


GridSearchCV(cv=5, error_score='raise',
       estimator=XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=-1, nthread=None, objective='binary:logistic',
       random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
       seed=None, silent=True, subsample=1),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'colsample_bytree': array([0.5, 0.9]), 'n_estimators': [100, 200], 'max_depth': [10, 15, 20]},
       pre_dispatch='2*n_jobs', refit=True, scoring=None, verbose=0)

In [48]:
# Find best model
best_xgb_model = CV_XGB.best_estimator_
print (CV_XGB.best_score_, CV_XGB.best_params_)

0.9664194269457428 {'colsample_bytree': 0.5, 'max_depth': 10, 'n_estimators': 200}


### Predictions on test set

In [49]:
y_pred_test=best_xgb_model.predict(x_test)

#### Accuaracy

In [50]:
print(accuracy_score(y_test,y_pred_test))

0.9706021811284969


In [51]:
# Create adaboost-decision tree classifer object
XGB_model = XGBClassifier(colsample_bytree = 0.5,
                          n_estimators=200,
                          max_depth=10)

%time XGB_model.fit(x_train, y_train)

# Predict on Test 
y_preds_train = XGB_model.predict(x_train)
y_preds_test = XGB_model.predict(x_test)

print("Train Accuracy", accuracy_score(y_train, y_preds_train))
print("Test Accuracy", accuracy_score(y_test, y_preds_test))


Wall time: 1min 15s
Train Accuracy 1.0
Test Accuracy 0.9706021811284969


In [52]:
# Print out classification report 
print(classification_report(y_test,y_preds_test))
#Print out confusion matrix
cmat = confusion_matrix(y_test, y_preds_test)
print(cmat)
sensitivity1 = cmat[0,0]/(cmat[0,0]+cmat[0,1])
print('Sensitivity : ', sensitivity1 )
print('Accuracy Rate: {}'.format(np.divide(np.sum([cmat[0,0],cmat[1,1]]),np.sum(cmat))))
specificity1 = cmat[1,1]/(cmat[1,0]+cmat[1,1])
print('Specificity : ', specificity1)


             precision    recall  f1-score   support

          0       0.97      0.98      0.97      4650
          1       0.97      0.96      0.97      3786

avg / total       0.97      0.97      0.97      8436

[[4535  115]
 [ 133 3653]]
Sensitivity :  0.975268817204301
Accuracy Rate: 0.9706021811284969
Specificity :  0.9648705758055995


In [53]:
# Print out classification report 
print(classification_report(y_train,y_preds_train))
cmat1 = confusion_matrix(y_train,y_preds_train)
print(cmat1)
sensitivity2 = cmat1[0,0]/(cmat1[0,0]+cmat1[0,1])
print('Sensitivity : ', sensitivity2 )
print('Accuracy Rate: {}'.format(np.divide(np.sum([cmat1[0,0],cmat1[1,1]]),np.sum(cmat1))))
specificity2 = cmat1[1,1]/(cmat1[1,0]+cmat1[1,1])
print('Specificity : ', specificity2)

             precision    recall  f1-score   support

          0       1.00      1.00      1.00     10972
          1       1.00      1.00      1.00      8712

avg / total       1.00      1.00      1.00     19684

[[10972     0]
 [    0  8712]]
Sensitivity :  1.0
Accuracy Rate: 1.0
Specificity :  1.0
