### K Nearest Neighbours

In [1]:
## Loading required Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
## Reading Both Train and Test Data
traindata = pd.read_csv("C:/Users/sirola/Downloads/CUTe/banktrain.csv")
testdata = pd.read_csv("C:/Users/sirola/Downloads/CUTe/banktest.csv")

In [3]:
traindata.shape

(19684, 34)

In [4]:
testdata.shape

(8436, 34)

In [5]:
y_train=traindata.loc[:,["target"]]

In [6]:
x_train=traindata.drop(['target'],axis=1)

In [7]:
y_test=testdata.loc[:,["target"]]
x_test=testdata.drop(['target'],axis=1)

In [8]:
# Import module for KNN
from sklearn.neighbors import KNeighborsClassifier
# Create KNN instance
# n_neighbors -> argument identifies the amount of neighbors used to ID classification
knn = KNeighborsClassifier(n_neighbors=8)
# Fit (i.e. training) the model
%time knn.fit(x_train, y_train)

E:\PYTHON\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """Entry point for launching an IPython kernel.


Wall time: 509 ms


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=8, p=2,
           weights='uniform')

In [9]:
# Use the .predict() method to make predictions from the x_test subset
pred = knn.predict(x_test)
pred1=knn.predict(x_train)
# Review the predictions
pred
pred1

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [10]:
# Import classification report and confusion matrix to evaluate predictions
from sklearn.metrics import classification_report, confusion_matrix

In [11]:
# Print out classification report and confusion matrix
print(classification_report(y_test, pred))

             precision    recall  f1-score   support

          0       0.80      0.84      0.82      4650
          1       0.79      0.74      0.77      3786

avg / total       0.80      0.80      0.80      8436



In [19]:
print(classification_report(y_train, pred1))

             precision    recall  f1-score   support

          0       0.84      0.89      0.86     10972
          1       0.85      0.79      0.82      8712

avg / total       0.84      0.84      0.84     19684



In [13]:
# Print out confusion matrix
cmat = confusion_matrix(y_test, pred)
print(cmat)
sensitivity1 = cmat[0,0]/(cmat[0,0]+cmat[0,1])
print('Sensitivity : ', sensitivity1 )
specificity1 = cmat[1,1]/(cmat[1,0]+cmat[1,1])
print('Specificity : ', specificity1)

print('TP - True Negative {}'.format(cmat[0,0]))
print('FP - False Positive {}'.format(cmat[0,1]))
print('FN - False Negative {}'.format(cmat[1,0]))
print('TP - True Positive {}'.format(cmat[1,1]))
print('Accuracy Rate: {}'.format(np.divide(np.sum([cmat[0,0],cmat[1,1]]),np.sum(cmat))))
print('Misclassification Rate: {}'.format(np.divide(np.sum([cmat[0,1],cmat[1,0]]),np.sum(cmat))))

[[3916  734]
 [ 966 2820]]
Sensitivity :  0.8421505376344086
Specificity :  0.7448494453248812
TP - True Negative 3916
FP - False Positive 734
FN - False Negative 966
TP - True Positive 2820
Accuracy Rate: 0.7984826932195354
Misclassification Rate: 0.20151730678046467


In [14]:
cmat1 = confusion_matrix(y_train, pred1)
print(cmat1)
sensitivity2 = cmat1[0,0]/(cmat1[0,0]+cmat1[0,1])
print('Sensitivity : ', sensitivity2 )
print('Accuracy Rate: {}'.format(np.divide(np.sum([cmat1[0,0],cmat1[1,1]]),np.sum(cmat1))))
specificity2 = cmat1[1,1]/(cmat1[1,0]+cmat1[1,1])
print('Specificity : ', specificity2)

[[9724 1248]
 [1842 6870]]
Sensitivity :  0.8862559241706162
Accuracy Rate: 0.843019711440764
Specificity :  0.7885674931129476


In [15]:
## trying with different value of k 
knn = KNeighborsClassifier(n_neighbors=7)
%time knn.fit(x_train, y_train)

E:\PYTHON\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """Entry point for launching an IPython kernel.


Wall time: 323 ms


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=7, p=2,
           weights='uniform')

In [16]:
# Review the predictions
pred = knn.predict(x_test)
pred

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [17]:
# Print out classification report and confusion matrix
print(classification_report(y_test, pred))

             precision    recall  f1-score   support

          0       0.83      0.82      0.82      4650
          1       0.78      0.80      0.79      3786

avg / total       0.81      0.81      0.81      8436



In [18]:
# Print out confusion matrix
cmat = confusion_matrix(y_test, pred)
#print(cmat)
print('TP - True Negative {}'.format(cmat[0,0]))
print('FP - False Positive {}'.format(cmat[0,1]))
print('FN - False Negative {}'.format(cmat[1,0]))
print('TP - True Positive {}'.format(cmat[1,1]))
print('Accuracy Rate: {}'.format(np.divide(np.sum([cmat[0,0],cmat[1,1]]),np.sum(cmat))))
print('Misclassification Rate: {}'.format(np.divide(np.sum([cmat[0,1],cmat[1,0]]),np.sum(cmat))))

TP - True Negative 3790
FP - False Positive 860
FN - False Negative 772
TP - True Positive 3014
Accuracy Rate: 0.8065433854907539
Misclassification Rate: 0.1934566145092461
